In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("../AQI_Data/processed_aqi_data.csv")

In [4]:
df.head()

,timestamp,location_name,location_lat,location_lon,co,no2,o3,pm10,pm25,so2,aqi,aqi_category,hour,day,month,year,day_of_week,is_weekend
0,2019-01-01 00:00:00,Delhi,28.7041,77.1025,0.598089,24.943655,18.081507,108.281832,75.196148,4.378213,221.629670,Poor,0,1,1,2019,1,0
1,2019-01-01 00:00:00,Faridabad,28.4089,77.3178,1.093698,5.699821,53.686134,56.260069,42.709284,6.493686,137.180953,Moderate,0,1,1,2019,1,0
2,2019-01-01 00:00:00,Ghaziabad,28.6692,77.4538,0.420770,19.419563,34.967340,82.842934,59.295449,4.423260,205.059468,Poor,0,1,1,2019,1,0
3,2019-01-01 00:00:00,Gurgaon,28.4595,77.0266,0.706815,30.585009,35.874847,117.015282,75.435553,7.511787,221.879156,Poor,0,1,1,2019,1,0
4,2019-01-01 00:00:00,Noida,28.5355,77.3910,0.542118,23.626271,39.401078,116.208836,68.843636,6.828320,215.009684,Poor,0,1,1,2019,1,0

In [5]:
df.columns

Index(['timestamp', 'location_name', 'location_lat', 'location_lon', 'co',
       'no2', 'o3', 'pm10', 'pm25', 'so2', 'aqi', 'aqi_category', 'hour',
       'day', 'month', 'year', 'day_of_week', 'is_weekend'],
      dtype='str')

In [6]:
df = df.drop(columns=[
    'aqi_category',
    'hour',
    'day',
    'month',
    'year',
    'day_of_week',
    'is_weekend'
])

In [8]:
df.shape

(219125, 11)

In [7]:
numeric_columns = df.select_dtypes(include=['int64', 'float64']).columns.tolist()

print("Numerical Columns:")
print(numeric_columns)

Numerical Columns:
['location_lat', 'location_lon', 'co', 'no2', 'o3', 'pm10', 'pm25', 'so2', 'aqi']

In [9]:
df.columns

Index(['timestamp', 'location_name', 'location_lat', 'location_lon', 'co',
       'no2', 'o3', 'pm10', 'pm25', 'so2', 'aqi'],
      dtype='str')

In [10]:
df.to_csv('../AQI_Data/AQI_cleaned.csv', index=False)

In [11]:
df.head()

,timestamp,location_name,location_lat,location_lon,co,no2,o3,pm10,pm25,so2,aqi
0,2019-01-01 00:00:00,Delhi,28.7041,77.1025,0.598089,24.943655,18.081507,108.281832,75.196148,4.378213,221.629670
1,2019-01-01 00:00:00,Faridabad,28.4089,77.3178,1.093698,5.699821,53.686134,56.260069,42.709284,6.493686,137.180953
2,2019-01-01 00:00:00,Ghaziabad,28.6692,77.4538,0.420770,19.419563,34.967340,82.842934,59.295449,4.423260,205.059468
3,2019-01-01 00:00:00,Gurgaon,28.4595,77.0266,0.706815,30.585009,35.874847,117.015282,75.435553,7.511787,221.879156
4,2019-01-01 00:00:00,Noida,28.5355,77.3910,0.542118,23.626271,39.401078,116.208836,68.843636,6.828320,215.009684